// Generated by CoffeeScript 1.9.2
(function() {
  var browserSync, config, gulp, plumber, reload, sourcemaps;

  config = require('./package.json');

  gulp = require('gulp');

  plumber = require('gulp-plumber');

  sourcemaps = require('gulp-sourcemaps');

  gulp.task('sass', function() {
    var sass;
    sass = require('gulp-sass');
    return gulp.src(config.path.src.styles + "/sass/**/*.{sass,scss}").pipe(plumber()).pipe(sourcemaps.init()).pipe(sass()).pipe(sourcemaps.write()).pipe(gulp.dest(config.path.build.css));
  });

  gulp.task('browserify', function() {
    var browserify, buffer, source;
    browserify = require('browserify');
    source = require('vinyl-source-stream');
    buffer = require('vinyl-buffer');
    return browserify(config.path.src.scripts + "/coffee/main.coffee", {
      extention: ['coffee', 'js'],
      debug: true
    }).transform('coffeeify').bundle().pipe(source('bundle.js')).pipe(buffer()).pipe(plumber()).pipe(sourcemaps.init({
      loadMaps: true
    })).pipe(sourcemaps.write()).pipe(gulp.dest(config.path.build.js));
  });

  gulp.task('copy', function() {
    gulp.src("src/scripts/lib/*.js").pipe(gulp.dest(config.path.build.js + "/lib"));
    gulp.src("src/styles/lib/*.css").pipe(gulp.dest(config.path.build.css + "/lib"));
    gulp.src("src/images/**/*").pipe(gulp.dest('build/assets/img'));
    return gulp.src(config.path.src.base + "/*.html").pipe(gulp.dest('build/'));
  });

  browserSync = require('browser-sync').create();

  reload = browserSync.reload;

  gulp.task('watch', function() {
    browserSync.init({
      server: "./build"
    });
    gulp.watch(config.path.src.styles + "/sass/**/*.sass", ["sass", reload]);
    gulp.watch(config.path.src.scripts + "/coffee/**/*.coffee", ["browserify", reload]);
    return gulp.watch(config.path.src.base + "/*.html", ["copy", reload]);
  });

  gulp.task('default', ["sass", "browserify", "copy", "watch"]);

}).call(this);
